version: '3.7'
services:
  db:
    image: mysql:5.6
    container_name: mysql-dump
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql